name: Publish the Rathole Images for different architectures
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Rathole Build
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Clone Rathole
        run: git clone https://github.com/rapiz1/rathole
      - uses: Swatinem/rust-cache@v2

      - name: Build Binary aarch64
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: aarch64-unknown-linux-musl
          toolchain: stable
          args: --locked --release --manifest-path rathole/Cargo.toml --no-default-features --features client,noise
          strip: true

      - name: Build Binary x86_64
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: x86_64-unknown-linux-gnu
          toolchain: stable
          args: --locked --release --manifest-path rathole/Cargo.toml --no-default-features --features client,noise
          strip: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set Lowercase Repository Name
        run: echo "REPO_LC=${REPO,,}" >> ${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      - name: Publish Docker Images
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}:latest